### ISSUE TITLE
1.0.0-rc1: "Process" (class) - ambiguity

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#307]
In EMMO-1.0.0-rc1: The **emmo:Process** class is described (and also classified as "A 'Process' is always a 'Physical', since a 'Void' does not have elements that evolves in time.".

I would argue that the "Process" itself is just a concept in our mind. It is, how we abstract (describe) and categorize the evolution of a physical object over time. "Physical" is what happens to the object (not it's abstract description). If the focus of the term should describing more the passive aspect of the changes of an object, like "aging process", "dissolving process", "melting process" then I would try to find a less ambiguous term.

**Process(Description)** in the meaning of describing a planned, step-wise change of a physical object, I would place in `Perceptual/Grapical/Symbolic/` (similar to ProgramCode/Software).

**Comment by markdoerr** [comment]
Here is an additional thought:

An additional differentiation between
**Process** - describing, **what** changes are made

and 

**Procedure** - describing, **how** changes are made

would be very useful.

**Comment by emanueleghedini** [comment]
Process and Object are addressed by the persistence perspective. Since EMMO is comparable to a 4D ontology, the distinction between process and object (or endurant and perdurant) don't make sense.

Instead, we define that an entitiy _x_ is an object according to a type _ϕ_  if _x_ all its temporal parts are of type _ϕ_. So, for example, if _ϕ_ is the class of human beings, then the 4D entity representing my life is an object. if _ϕ_ is the class of students, the 4D entity representing my life is a process, since I'm no more a student.

Procedure in 1.0.0-rc3 now is described as an intentional process drived by an intentional agent referring to a plan, the latter being a document, idea, algorithm,... (see EMMO agency module)
