### ISSUE TITLE
How to model abstract concepts, like a hypothesis, a synthesis idea, an algorithm in EMMO ?

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#309]
Since EMMO is also a top level ontology for many scientific eras, 
shouldn't it be able to also describe abstract concepts, like
a hypothesis of an experiment, a chemical synthesis idea, an algorithm for a computer program ?

How would one model such abstract concepts in EMMO ?

**Comment by jesper-friis** [comment]
EMMO is nomenalistic. So abstract concepts are described by classes. 
All individuals must stand for real world entities.

**Comment by emanueleghedini** [comment]
Hypothesis, synthesis ideas, algorithms are quite different things and not abstract entities. What goes under the term 'abstract' is really extremely broad and not univocally defined (https://plato.stanford.edu/entries/abstract-objects/)

For example: algorithms are represented using standardised representations. So an algorithm is e.g., a flow chart, a text, that may be the starting point for a derived entity such as the program implementing it. The design of a bridge is a set of documents (drawings, numbers, simulations, schematics) and the real bridge is an entity standing for the blueprint (and viceversa, depending on the perspective). Also an idea is a mental representation. 

So no abstract entities here. What you called idea, hypothesis, algorithm, is simply a data entity. On paper, electronic device, neuron, ...

If with abstract you refer to entities outside space and time, then they simply don't exist as physical entities and we don't speak about what we cannot speak of ;-)

If you refer to general ideas of e.g. cat, than we are pure nominalistics: the idea of a cat is simply the set of all entities identified as cats. So classes, for the EMMO, are the entities representing this archetypal ideas and individuals are instances, i.e. that specific cat, and the rdf:type relation is the instantiation. 
In other ontologies there is the possibility to declare an instantiation relation between individuals, so that one is of higher order than another. We don't think this is the best approach for an ontology based on scientific evidences.
