### ISSUE TITLE
1.0.0-rc1: "Vacuum" really a subclass of "Field" ?

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMO#310]
in EMMO- 1.0.0-rc1  **Vacuum** class is defined as a subclass of **Field** . As modern (Quantum-) Physics still struggles
describing the nature of a "field" and it's relation to "matter" (or vacuum, which is per definitionem the absence of all matter, in its pure form a more theoretical concept / idea), I am wondering, why the EMMO designers used that class-subclass relation ?

It would be nice to read some elucidations in the class annotations of "Vacuum".

(another question is, if something like "the complete absence of matter" can be described with the present EMMO concepts, since it fits more in the category of ideas, like hypothesis, plans, strategies, algorithms. The same might hold true with "fields" since they are also massless => philosophically quite a challenging problem ).

**Comment by jesper-friis** [comment]
Vacuum was removed when the physicalistic module was reworked during the spring. It was defined as absence of matter particles (but not necessary absence of e.g. a gravitational field).

EMMO cannot describe complete absence of anything. But absence of matter particles (or availability of only photons and gravitons) is possible to describe.

**Comment by emanueleghedini** [comment]
> in EMMO- 1.0.0-rc1 **Vacuum** class is defined as a subclass of **Field** . As modern (Quantum-) Physics still struggles describing the nature of a "field" and it's relation to "matter" (or vacuum, which is per definitionem the absence of all matter, in its pure form a more theoretical concept / idea), I am wondering, why the EMMO designers used that class-subclass relation ?
> It would be nice to read some elucidations in the class annotations of "Vacuum".
As said by Jesper the concept of **Vacuum** is no more in the new mereocausal description of physical entities, since now the spacetime is no more the fabric upon which everything is placed, but space and time are reconstructed from the causal network, whose nodes are elementary particles and edges are the fundamental forces. The existence of a quantum field affecting elementary particles is now represented as bi-directional causal relation (an object property) between them standing for virtual particles (i.e., for all possible Feynman diagrams). The existence of a classical field is represented as a causal chain from one entity to another reapresenting e.g., a 'real' photon travelling from one molecule to another.  

> (another question is, if something like "the complete absence of matter" can be described with the present EMMO concepts, since it fits more in the category of ideas, like hypothesis, plans, strategies, algorithms. The same might hold true with "fields" since they are also massless => philosophically quite a challenging problem ).
In EMMO matter is not as fundamental as physical entity, since photon is not matter, but still physically interacts with other entities. Absence of evolving physical entities is simply nothingness, you can't represent nothing.

We will develop a module for fields, in mathematical sense: fields are now simply mathematical models to describe a fundamental causal interaction.

By the way, the EMMO is now way more subtle in treating reality that it was in the past, and consider causality more relevant with respect to spacetime. If you are interested in phylosophical implication of such approach, please contact me.
