### ISSUE TITLE
How to model the concept of Coating

### ISSUE THREAD

**Issue by pierluigidelnostro** [emmo-repo/EMMO#317]
For example, in case of a coating characterisation testing there is a Sample that has a Coating which is the actual object of the test.
I would model this using Tiles, where one tile is the support, made of a certain material, and another tile is the coating made of another material. Is that correct? Any suggestions?
I would suggest considering to add the concept of Coating to EMMO, instead of having it in a domain ontology as CHAMEO. The CoatingManufacturing process is already there.
Thanks

**Comment by lattaai8** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add a new Coating class as a subclass of ManufacturedProduct, and update the CoatingManufacturing process to relate to it.

You can review changes in this commit: https://github.com/lattaai8/emmo-repo-EMMO-317/commit/e618c1eff08e72a40c9bfd645f1b9e9dd6a6dbfa.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by emanueleghedini** [comment]
Addressed during EMMO development meeting. The suggestion will be implemented by Pierluigi in a dedicated ontology and eventually moved to the EMMO official manufacturing module.
