### ISSUE TITLE
Add Intentional processes

### ISSUE THREAD

**Issue by ahashibon** [emmo-repo/EMMO#32]
In technological applications many actions are intentional. We need to cover it in EMMO. 

A proposal to add a "triangle with a central element" similar to Semiotic Triangle is suggested: 

nodes: 

1. physical representing the thing that is subject to the action. This physical has properties associated with in in a semiotic process that are subject to change as a result (note the action is not on the properties as wrongly attributed in some process description, but on the thing (physical) itself)
2. physical representing the rendered or operated on the thing above (also physical) along with its new properties (again obtained by new semiotic processes) 
3. The "intentional" representing the plan, i.e., the change (e.g.,  cut a sample, pull a sample, or an entire set of steps like an algorithm, or a step in an algorith, or a MODA workflow, etc) 

the center of the triangle has the agent. 

All the above is contained in an intentional process, like the sign, object etc are contained in the semiotic process. 

The semiotic process can also have its on "intentional triangle" to describe how the measurement is done for example, and by whom etc.

**Comment by emanueleghedini** [comment]
Intentionality may be expressed meta-ontologically by simply describing the planned action in the EMMO 4D approach, as if it were already happened. You know that is a plan and not "real" because you put a stamp on the representation for the ontology readers.

The above process can be described within the EMMO (including who planned the action). A plan may be a information entity (e.g. a document, a speech, a diagram) that represent a process that may occur. In that sense it already falls under the semiotic branch, as a sign (the plan) that stands for an object (the action).  Observation processes at the end of the actions may compare the planned properties with the observed properties.

We can of course include it under the semiotic branch, by declaring a subclass of semiosis called Planning, or IntentionalityProcess.
